apiVersion: v1
kind: ReplicationController
metadata:
  name: myrc
  labels:
    name: nginx
    type: front-end
spec:
  replicas: 3
  template:
    metadata:
      name: mypod
      labels:
        app: nginx
        type: front-end
    spec:
      containers:
        - name: nginx
          image: nginx