apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
  labels:
    name: nginx
    type: front-end
spec:
  selector:
    matchLabels:
      app: nginx
      type: front-end
  replicas: 3
  template:
    metadata:
      name: mypod
      labels:
        app: nginx
        type: front-end
    spec:
      containers:
        - name: nginx
          image: nginx
    